apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  uid: prometheus
  jsonData:
    httpMethod: GET
    timeInterval: 15s
    exemplarTraceIdDestinations:
      - name: traceId
        datasourceUid: Tempo
  version: 1
  editable: false
  basicAuth: false