apiVersion: 1

datasources:
- name: Tempo
  type: tempo
  access: proxy
  url: http://tempo:3200
  uid: Tempo
  jsonData:
    tracesToLogsV2:
        datasourceUid: Loki
        spanStartTimeShift: -5m
        spanEndTimeShift: 5m
        filterByTraceID: true
    tracesToMetrics:
        datasourceUid: Prometheus # Link to Prometheus
        spanStartTimeShift: -5m
        spanEndTimeShift: 5m
